version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    ports:
      - 8000:8000
    networks:
      - adpnet
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0.29
    ports:
    - '3306:3306'
    volumes:
      - ../db_app:/var/lib/mysql
    env_file:
      - .env
    networks:
      - adpnet
    restart: always

networks:
  adpnet:
    driver: bridge
