version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0:8000
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    volumes:
      - .:/adp
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0.29
    ports:
    - '3306:3306'
    volumes:
      - ../db_app:/var/lib/mysql
    env_file:
      - .env
#    environment:
#      MYSQL_DATABASE: "${MYSQL_DATABASE}"
#      MYSQL_USER: "${MYSQL_USER}"
#      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always

volumes:
  static_volume:
  db_app:
