version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0:8000
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    ports:
      - 8000:8000
    networks:
      - adpnet
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0.29
    ports:
    - '3306:3306'
    volumes:
      - ../db_app:/var/lib/mysql
#    env_file:
#      - .env
    networks:
      - adpnet
    environment:
      MYSQL_DATABASE: "adp"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "qwerty"
      MYSQL_ROOT_PASSWORD: "qwerty"
#      MYSQL_DATABASE: "${MYSQL_DATABASE}"
#      MYSQL_USER: "${MYSQL_USER}"
#      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always

networks:
  adpnet:
    driver: bridge
